# Generated by Django 2.1.7 on 2019-02-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='handle',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='frontend/public/posts/%Y/%m/%d', verbose_name='posts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='frontend/public/users/%Y/%m/%d', verbose_name='users'),
        ),
    ]
