# Generated by Django 2.2.2 on 2019-07-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_rename_image_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='frontend/public/post_pictures/%Y/%m', verbose_name='post_picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='frontend/public/profile_pictures/%Y/%m', verbose_name='profile_picture'),
        ),
    ]
